name: demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world!!!"
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: kirasemifir.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: docker build . -t kirasemifir.azurecr.io/demo
    - run: docker push kirasemifir.azurecr.io/demo